from typing import Any

from spotipy.oauth2 import SpotifyOAuth

class Spotify:
    def __init__(self, auth_manager: SpotifyOAuth | None = ...) -> None: ...
    def me(self) -> dict[str, Any]: ...
    def current_user(self) -> dict[str, Any]: ...
    def current_user_playlists(self, limit: int = ...) -> dict[str, Any] | None: ...
    def next(self, result: dict[str, Any]) -> dict[str, Any] | None: ...
    def playlist_items(
        self,
        playlist_id: str,
        additional_types: list[str] | None = ...,
    ) -> dict[str, Any] | None: ...
    def playlist(self, playlist_id: str) -> dict[str, Any] | None: ...
    def playlist_change_details(
        self,
        playlist_id: str,
        name: str | None = ...,
        description: str | None = ...,
        public: bool | None = ...,
    ) -> None: ...
    def playlist_replace_items(self, playlist_id: str, items: list[str]) -> None: ...
    def playlist_add_items(self, playlist_id: str, items: list[str]) -> None: ...
