name: Continuous Integration for Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Test main package
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.14"
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # https://github.com/astral-sh/setup-uv/releases/tag/v9.0.0
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: make setup-ci

      - name: Static analysis
        run: make static

      - name: Run unit tests on codebase
        run: make test-unit
